AOS Fog of War: FischlWorks_FogWar.Shadowcaster Class Reference
FischlWorks_FogWar.Shadowcaster Class Reference
A non-static submodule that performs shadowcasting algorithm over a LevelData object.
Classes
class FogField
class LevelColumn
Public Member Functions
void Initialize (csFogWar fogWar)
Initializes the shadowcaster module with properties from the dependant csFogWar object.
void ProcessLevelData (Vector2Int revealerPoint, int sightRange)
Processes the level data with shadowcasting algorithm, and updates the FogField object accordingly.
void ResetTileVisibility ()
Resets all tile's visibility info.
Properties
FogField fogField = new FogField() [get]
Detailed Description
A non-static submodule that performs shadowcasting algorithm over a LevelData object.
An instance of this module is instantiated for each construction of the csFogWar object.
While the LevelData class defined within csFogWar class holds the information about obstacles,
the FogField class defined within Shadowcaster class holds the information about player sight.
Member Function Documentation
Initialize()
void FischlWorks_FogWar.Shadowcaster.Initialize (csFogWar fogWar) inline
Initializes the shadowcaster module with properties from the dependant csFogWar object.
        {
            this.fogWar = fogWar;
            for (int xIterator = 0; xIterator < fogWar.levelData.levelDimensionX; xIterator++)
            {
                // Adding a new list for column (y axis) for each unit in row (x axis)
                fogField.AddColumn(new LevelColumn(Enumerable.Repeat(LevelColumn.ETileVisibility.Hidden, fogWar.levelData.levelDimensionY)));
            }
            quadrantIterator = new QuadrantIterator(fogWar);
        }
ProcessLevelData()
void FischlWorks_FogWar.Shadowcaster.ProcessLevelData (Vector2Int revealerPoint, int sightRange) inline
Processes the level data with shadowcasting algorithm, and updates the FogField object accordingly.
        {
            // Reveal the first tile where the revealer is at
            RevealTile(fogWar.WorldToLevel(revealerPoint));
            // Give the quadrant iterator the revealer's position
            quadrantIterator.originPoint = revealerPoint;
            // We deal with 90 degrees each, anti-clockwise, starting from east to west
            foreach (int cardinal in System.Enum.GetValues(typeof(QuadrantIterator.ECardinal)))
            {
                quadrantIterator.cardinal = (QuadrantIterator.ECardinal)cardinal;
                // Here goes the BFS algorithm, we queue a new pass during each pass if needed, then start the new one
                Queue<ColumnIterator> columnIterators = new Queue<ColumnIterator>();
                // The first pass of the given quadrant, start from slope -1 to slope 1
                columnIterators.Enqueue(new ColumnIterator(1, sightRange, -1, 1));
                while (columnIterators.Count > 0)
                {
                    ColumnIterator columnIterator = columnIterators.Dequeue();
                    // Note that the given points may have negative y values instead of starting from zero
                    List<Vector2Int> quadrantPoints = columnIterator.GetTiles();
                    // This is to detect points where the obstacle tile and the empty tile are adjacent
                    Vector2Int lastQuadrantPoint = new Vector2Int();
                    // This is to skip the first pass where the lastQuadrantPoint variable is not assigned yet
                    bool firstStepFlag = true;
                    foreach (Vector2Int quadrantPoint in quadrantPoints)
                    {
                        if (IsTileObstacle(quadrantPoint) == true || IsTileVisible(columnIterator, quadrantPoint))
{
                            RevealTileIteratively(quadrantPoint, sightRange);
                        }
                        if (firstStepFlag == false)
{
                            if (IsTileObstacle(lastQuadrantPoint) == true && IsTileEmpty(quadrantPoint) == true)
{
                                columnIterator.startSlope = GetQuadrantSlope(quadrantPoint);
                            }
                            if (IsTileEmpty(lastQuadrantPoint) == true && IsTileObstacle(quadrantPoint) == true)
{
                                if (columnIterator.IsProceedable() == false)
{
                                    continue;
                                }
                                ColumnIterator nextColumnIterator = new ColumnIterator(
                                    columnIterator.depth,
                                    sightRange,
                                    columnIterator.startSlope,
                                    GetQuadrantSlope(quadrantPoint));
                                nextColumnIterator.ProceedIfPossible();
                                columnIterators.Enqueue(nextColumnIterator);
                            }
                        }
                        lastQuadrantPoint = quadrantPoint;
                        firstStepFlag = false;
                    }
                    if (IsTileEmpty(lastQuadrantPoint) == true && columnIterator.IsProceedable() == true)
                    {
                        columnIterator.ProceedIfPossible();
                        columnIterators.Enqueue(columnIterator);
                    }
                }
            }
        }
ResetTileVisibility()
void FischlWorks_FogWar.Shadowcaster.ResetTileVisibility () inline
Resets all tile's visibility info.
        {
            fogField.Reset();
        }
Property Documentation
fogField
FogField FischlWorks_FogWar.Shadowcaster.fogField = new FogField() get
{ get; private set; } = new FogField();
Referenced by FischlWorks_FogWar.csFogWar.CheckVisibility(), FischlWorks_FogWar.Shadowcaster.Initialize(), and FischlWorks_FogWar.Shadowcaster.ResetTileVisibility().
The documentation for this class was generated from the following file:
C:/Users/keith/Desktop/HomebrewFogofwar/Assets/AOSFogWar/Shadowcaster.cs